url: "https://tehbrian.xyz"

plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag

exclude: ["README.md", "LICENSE", "CNAME"]

defaults:
    - scope:
          path: ""
      values:
          author: "TehBrian"
