url: "https://tehbrian.xyz" # the base hostname & protocol for your site

plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag

exclude: ["README.md", "LICENSE", "CNAME"]

collections:
  pages:
    output: true
    permalink: /:path

defaults:
    - scope:
          path: ""
      values:
          layout: "default"
